title: Jasmine Moore's Personal Blog
email: jamoo@jamoo.dev
description: >-
  Jasmine Moore's personal blog. Tech, learning, thought: Her bastion against information entropy.
baseurl: "/"
url: "https://jamoo.dev/"
twitter_username: freeone3000
github_username: freeone3000
safe: false

plugins:
 - jekyll-coffeescript
 - jekyll-default-layout
 - jekyll-gist
 - jekyll-github-metadata
 - jekyll-optional-front-matter
 - jekyll-paginate
 - jekyll-readme-index
 - jekyll-titles-from-headings
 - jekyll-relative-links


